### ISSUE TITLE
Timestamp offset issue (Stoken expired error)

### ISSUE THREAD

**Issue by chrisjohnson** [slushie/recaptcha-secure-token#6]
I'm opening an issue here not because your code is wrong but because I'm thinking if we can come up with a way to correct the problem, it will be here.

Seems like the algorithm is dependent upon your local time being exactly synced with google's time. If your time is ahead of google's time, your token will show as expired every time.

For now I have fixed this by manually passing the $timestamp argument as 30 seconds ago, which seems to work both on my prod server (where the Stoken expired error first came up) and on my dev server (which has always worked fine).

I'm not sure if there is something we can do to detect the different in times? Maybe I just need to call this code from an ajax request from within the browser which sends the user's local time? Do you have any clue how it actually determines which timestamp you should be sending? What is the margin for error?

Anyway if you have any thoughts or suggestions I'd be glad to hear them. I also opened a google discussion post before I had figured out what was going wrong: https://groups.google.com/forum/#!topic/recaptcha/bkh8oTqInIg

**Comment by slushie** [comment]
Because of the nature of this protocol, its important to maintain an accurate system clock. I would _not_ recommend using the user's clock, as that is most likely to be much less accurate than your server's. Instead, run `ntpdate` on your server to keep the clock accurate.

If you cannot adjust the system clock on your server (maybe you have no root access), you could request the time from an NTP server manually via PHP. A cursory Google search turned up [this library](https://github.com/bt51/ntp) to fetch the time over NTP.

I don't know if the actual timeout is specified anywhere within Google's documentation, but I'd expect the clocks should be synchronized to within 2 minutes.

NB: the `timestamp` value is not "local time" but "milliseconds since the UNIX epoch", which is midnight on January 1, 1970 in UTC. That is a monotonic clock (no time zones or daylight savings time), merely counting milliseconds.

**Comment by chrisjohnson** [comment]
I appreciate your response. Would you be opposed to a pull request where I implemented an (optional) feature to pull from an NTP server rather than using server time? I could do it externally to this lib but it just seems like a feature that is critical to the operation of this lib and so it should, for portability sake, be bundled in. Given that the currentTimestamp method is already implemented in this lib too it seems logical to offer the NTP discovery method here as well. What are your thoughts? I would likely add the library you mentioned as a dependency to do so.

**Comment by slushie** [comment]
I think that NTP is well outside of the scope of this library. The `secureToken()` method already accepts a `$timestamp` parameter that library consumers (eg, you) can use to provide any timestamp value.

If you want to provide an NTP-based workaround to an incorrect system clock, simply sending the timestamp from your NTP client to the `secureToken()` method would solve the issue. Adding a dependency would add significant complexity for all users of this library in order to save a few lines of code (not adding any functionality) for edge cases.

**Comment by chrisjohnson** [comment]
Well my thought process is:

This library needs a _synced_ timestamp
This library implements code to retrieve a timestamp from the system time, which may or may not be synced
Therefore, the library is not currently meeting its own needs, merely relying on an external system being correct (microtime()) with no explicit definition of this dependency

Honestly it wouldn't even save any lines of code, since it will take the same lines of code to make the request inside or outside of the library. My aim isn't laziness, I'm just talking about the logical dependency that exists here without being explicitly defined or fulfilled.

FWIW this discussion with you is the first time I've even heard of the timestamps needing to be in sync. If you still disagree with my suggestion to build the feature in perhaps you could at least mention it in the README? It's obviously something that this library needs but there's no way to know that and if the library isn't meeting its needs internally it should at least be documented that you need to make changes externally to fit

**Comment by slushie** [comment]
I do believe that NTP is outside the scope of this library, even though an accurate clock is a hard dependency. Timestamps can be generated in any number of ways and it would be a mistake to require NTP to do so -- especially since there is an existing language feature already available.

I think there is an expectation that time-based protocols require accurate system clock. That being said, I definitely think that requirement should be expressed in the README, which is currently the only documentation available for this protocol.

If you'd like to submit a PR to update the README, that would be great. Otherwise I will make the changes later today.

**Comment by chrisjohnson** [comment]
To be honest I wasn't even aware that it was a time-based protocol until I started digging into the library source. From the name "token" I got the idea that it was requesting an auth token from google, not generating one based on local timestamp. I will submit a PR later tonight
