### ISSUE TITLE
\ReCaptchaSecureToken\ReCaptchaToken::currentTimestamp()

### ISSUE THREAD

**Issue by ucavus** [slushie/recaptcha-secure-token#8]
You've used `round()` which returns a `float` type. This does not reliably return integer output as specified in Google's API. You're better off forcing it to be decimal like so:

``` PHP
return number_format(microtime(true), 3, '', '');
```

Whilst that does return a `string`, its format is guaranteed, Google accepts it without issue, and casting to `int` would overflow on 32-bit systems.

**Comment by slushie** [comment]
The JSON `number` type makes no distinction between integral and floating point values. So a compliant JSON parser should treat the values `12.0` and `12` exactly the same way. However, there is a distinct JSON `string` type. A compliant JSON parser may treat the values `"12"` and `12` as distinct values.

Can you give an example in which `round($value)` would return a value that **would not** have zero precision, [as specified in the documentation](http://php.net/round)? Further, although undocumented, [PHP seems to treat zero-precision floats as integers](https://3v4l.org/g0J6F) within `json_encode()`. So functionally, `json_encode(['a' => 1.0]) === json_encode(['a' => 1])`.

Finally, it should be noted that there is no "Google API" for the secure token format, only example code. Even in a hypothetical the case that `round()` does not behave as documented, it follows that (a) PHP's "large numerical type" is `float`, (b) `float` becomes a JSON `number` within `json_encode()`, and thus (c) it is better to represent numbers using the type `float` rather than with the `string` type.

I'm going to close this issue because I think that should satisfactorily answer the question, but if you can give me a contradictory example I will re-open it.
